version: '0.2'
sources:
- database: local
  link: ''
  type: local
  branch: master
  cache_path: ''
  cache_timestamp: ''
  filters: null
- database: poo
  link: https://github.com/qxcodepoo/arcade.git
  type: clone
  branch: master
  cache_path: ''
  cache_timestamp: '2025-12-14 22:43:16'
  filters:
  - herança
expanded:
- poo@campanha-principal
- poo@bloco_f-herança-i
tasks:
  poo@zoo: '{rate:100, human:sim, iagen:sim, guide:sim, alone:8, study:180}'
  poo@pagamento: '{rate:100, human:sim, iagen:sim, guide:sim, alone:6, study:360}'
  poo@estacionamento: '{rate:100, human:sim, iagen:sim, alone:5, study:360}'
flags:
  quests: 0
  tracks: 0
  tasks: 1
  graph: 1
  xray: 0
lang: py
selected: poo@estacionamento
